language: python

env:
  global:
    # Doctr deploy key for pyflyby/pyflyby
    - secure: "rT3KNEN4zfVPtQstm6LpAa+maL6YBG2FDAKQg7UIAMZLNLQp/lQKF3X1LRAACIGU925KYSLYW/4Ly1YqddK137sgw62tndCb2Llx2v3gNa9Ew4GxG5b7Z2Ase5lu4t69AP/ka5mFhpTZJ4MBJoPvw7iw/Vom9jUoypxLhy/+EvCmGwX/HeYbrjEPhyYPIrREH5wLXHru/XMVI0qaqWviIab0CCvqEWehRqHs1k6CoS5hPeBTJnIJzqa34Xl3O88ECwMFnpg5ap9+02hDV1vfMxJehghynHWG2feyTxjGLtcmQMrLFXQDsLtQUq6DIjKDWMrjGpgj1Jb5HnYa8Kn+FBBmZd9QnVtFCIsW/hEPdyVkiYNYysFqHSI1Mfr/Lnhy1irP2vLi/YfJ82GV5k9a8FTy/IlbwEbmXsrCESEN/GGqUrTP+FvbXRBG767ykZ7gnRNKNbITVoQn/loenzh+8bkVR9luhalUBI7n/i2ayhV9iWeg8ZacOcj+4nwJJbJMZgLlFJMjs86ZWcUpjMWZB2ZaDRSKD9LGMfiJ8AzH/lsMK797ytPWLUX3ah2utEbLLBTRv2Kaj24Dj0LbHk/ZvlVl8Ut6TRs2uy5LIq3bHW9x58VU2PVhrf5B6M6XUhkzH/zFszEipgWobZRZys+h4FZb1d7pg1bqnl9R9L82Q38="

python:
  - 2.7

matrix:
  include:
    - python: 2.7
      env:
        - TESTS="true"
    - python: 3.7
      dist: xenial
      env:
        - TESTS="true"
    - python: 3.7
      env:
        - DOCS="true"

install:
  - set -e
  - pip install -U pip
  # Install prompt-toolkit from git until a release is made with
  # PROMPT_TOOLKIT_NO_CPR environment variable support.
  # Install jupyter_console from
  # https://github.com/jupyter/jupyter_console/pull/187 until it is included
  # in a release.
  # Install ipykernel from master until a version after 5.1.2 is released.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        pip install -U "pexpect>=3.3" pyflakes pytest epydoc rlipython requests jupyter flaky flake8;
    else
        pip install -U git+https://github.com/asmeurer/jupyter_console@display_completions;
        pip install -U "pexpect>=3.3" pyflakes pytest rlipython requests jupyter flaky flake8;
    fi
  - if [[ "${DOCS}" == "true" ]]; then
        pip install sphinx sphinx_rtd_theme sphinx-autodoc-typehints;
    fi
  - pip list

script:
  - set -x
  - set -e
  - shopt -s extglob globstar
  # pyflakes all files except for known_imports/*, etc/*, and __init__.py,
  # which are all unused imports. We use flake8 so we can use noqa if
  # necessary.
  - |
    if [[ "${TESTS}" == "true" ]]; then
        flake8 --exclude known_imports,etc,__init__.py --select=F;
    fi
  # Test for invalid escape sequences (will be syntax errors in a future
  # Python version)
  - |
    if [[ "${TESTS}" == "true" ]]; then
        python -We:invalid -m compileall -f -q lib/ etc/;
    fi
  - |
    if [[ "${TESTS}" == "true" ]]; then
        export DEBUG_TEST_PYFLYBY=1;
    fi
  - |
    if [[ "${TESTS}" == "true" ]]; then
        pytest --doctest-modules lib tests;
    fi
  # Smoke test tidy-imports on the codebase. This only fails if there is an
  # exception from a bug, but we could also make it fail if there are imports
  # that need to be tidied.
  - |
    if [[ "${TESTS}" == "true" ]]; then
        ./bin/tidy-imports -d lib/python/ tests/;
    fi
  - |
    if [ "${DOCS}" = "true" ]; then
        cd doc;
        make html;
        cd ..;
        pip install doctr;
        doctr deploy .;
    fi
