language: python

sudo: false
python:
  - 2.7

matrix:
  include:
    - python: 2.7
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - set -e
  - pip install -U pip
  - pip install sphinx sphinx_rtd_theme sphinx-autodoc-typehints
  # Install prompt-toolkit from git until a release is made with
  # PROMPT_TOOLKIT_NO_CPR environment variable support.
  # Install jupyter_console from
  # https://github.com/jupyter/jupyter_console/pull/187 until it is included
  # in a release.
  # Install ipykernel from master until a version after 5.1.2 is released.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        pip install -U "pexpect>=3.3" pyflakes pytest epydoc rlipython requests jupyter flaky flake8;
    else
        pip install -U git+https://github.com/asmeurer/jupyter_console@display_completions;
        pip install -U "pexpect>=3.3" pyflakes pytest rlipython requests jupyter flaky flake8;
    fi
  - pip list

script:
  # - set -x
  - shopt -s extglob globstar
  # pyflakes all files except for known_imports/*, etc/*, and __init__.py,
  # which are all unused imports. We use flake8 so we can use noqa if
  # necessary.
  - flake8 --exclude known_imports,etc,__init__.py --select=F
  # Test for invalid escape sequences (will be syntax errors in a future
  # Python version)
  - python -We:invalid -m compileall -f -q lib/ etc/;
  - export DEBUG_TEST_PYFLYBY=1
  - pytest --doctest-modules lib tests
  - cd doc
  - make html

after_success:
  - ./doc/push_docs.sh

env:
  global:
    - secure: "W6JE7GsO3VlM30I++g2xaJE4IRKkZna7oyL94DNO2DDSZe/yO6qjYEa1gOqMUie38U1J5MErd9ZYHmuLUsy6Kc3miG9Hw6TVVKhUre4uo4SS2pzgRaMt7F3PBh5DoKMPKDotmcUprH3NYwnEofIApQhQ6xlAxkvFlbvr4Z1oRb/Q4rdspqYmpem+irmNPQXS/s7CRFy0c/WEFWyfeZew0Xvg9Fe2R72CSRUCnrGQAhQ1/w3jM1O9g2/2HQdvUUcF0rBtPBxbxRAFI07HDSQKu9WfsAURVI1k52h/VSWaKToGzW5iA4Nb5601wfzJmAXHBeE82AMVbIi6S3T5dJVstHvpOP7Scq+dDjNVszBH1DA8w2gSGSZMIesWs28OCBQhdxoVt4jbw9euG0mctsIB5qYzRqaNUQc4GMZneJO18n0x+Mms/n213+3oEN1BjNRjmZFJtrmXuxuGKOKWMIAPaSv7QgjinsFJMf5oEOLV/uLfOTt0C5hG+WUiQuBvsj7E6DgJwTxU1huaK9utIujwBPgp5WHUUVVhYN0AbSuNqRe6zjg3VJ7RaDJpl8iY9JtUesK1Jc59aDj8wPGE+mbAjuez3QtEhSuOwfx6ws+yGW3FKjsOLmCbKJ8pKHz1xmKO6/9iUO+CxsyQe+Dj0GEaW1kzx7GVJUk6jA3XiQRMgM4="
